server.port=${PORT:5000}

# MongoDB configuration
spring.data.mongodb.uri=${MONGODB_URI:mongodb+srv://adhithyanms:adhi%40123@cluster0.0047sok.mongodb.net/ORRS?retryWrites=true&w=majority&appName=Cluster0}

# JWT Security
jwt.secret=${JWT_SECRET:devconnect_jwt_secret_key_2024_secure_token}

# Cloudinary properties
cloudinary.cloud-name=${CLOUDINARY_CLOUD_NAME:dpwtohaz0}
cloudinary.api-key=${CLOUDINARY_API_KEY:555746737368663}
cloudinary.api-secret=${CLOUDINARY_API_SECRET:QicpAD2347iApB_NxirYDsuEz6U}

# File Upload limits
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=15MB
